framework:
    messenger:
        failure_transport: failed
        reset_on_message: true
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    multiplier: 1
                options:
                    queue_name: async
                    auto_setup: true
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0            
                options:
                    queue_name: failed
                    auto_setup: true
            # sync: 'sync://'

        routing:
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
             'App\Message\AppMessage': async
